// <auto-generated />
using System;
using CodeJam5ProjectManagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeJam5ProjectManagement.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20240926152135_initialDataAndModels")]
    partial class initialDataAndModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeJam5ProjectManagement.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("EmployeeId");

                    b.ToTable("employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            FirstName = "Mahlon",
                            LastName = "Reese"
                        },
                        new
                        {
                            EmployeeId = 2,
                            FirstName = "Jonathan",
                            LastName = "Lun"
                        },
                        new
                        {
                            EmployeeId = 3,
                            FirstName = "Cyber",
                            LastName = "Justin"
                        });
                });

            modelBuilder.Entity("CodeJam5ProjectManagement.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId");

                    b.ToTable("statuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            StatusName = "Backlog"
                        },
                        new
                        {
                            StatusId = 2,
                            StatusName = "In Progress"
                        },
                        new
                        {
                            StatusId = 3,
                            StatusName = "Ready For Testing"
                        },
                        new
                        {
                            StatusId = 4,
                            StatusName = "Completed"
                        });
                });

            modelBuilder.Entity("CodeJam5ProjectManagement.Story", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("story_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoryId"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employee_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("StoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("story_name");

                    b.HasKey("StoryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StatusId");

                    b.ToTable("stories");

                    b.HasData(
                        new
                        {
                            StoryId = 1,
                            StatusId = 1,
                            StoryName = "Fix Bug"
                        },
                        new
                        {
                            StoryId = 2,
                            EmployeeId = 3,
                            StatusId = 2,
                            StoryName = "Hack Mainframe"
                        });
                });

            modelBuilder.Entity("CodeJam5ProjectManagement.Story", b =>
                {
                    b.HasOne("CodeJam5ProjectManagement.Employee", null)
                        .WithMany("stories")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("CodeJam5ProjectManagement.Status", null)
                        .WithMany("stories")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeJam5ProjectManagement.Employee", b =>
                {
                    b.Navigation("stories");
                });

            modelBuilder.Entity("CodeJam5ProjectManagement.Status", b =>
                {
                    b.Navigation("stories");
                });
#pragma warning restore 612, 618
        }
    }
}
